UPDATE FWK_PARAMETER SET PRM_VALUE = '02.03.00' WHERE PRM_ID = 3041;


-- Création de la table pour des sites
CREATE TABLE SITE (
	SIT_ID NUMBER(19,0) NOT NULL,
	SIT_NAME VARCHAR2(50 CHAR) NOT NULL,
	AGC_ID NUMBER(19,0) NOT NULL,
	CONSTRAINT PK_SITE PRIMARY KEY(SIT_ID) USING INDEX TABLESPACE TBS_ABITA_IDX,
	CONSTRAINT FK_SIT_2_AGC FOREIGN KEY (AGC_ID) REFERENCES AGENCY (AGC_ID)
);

-- Création de la séquence pour la table des sites
CREATE SEQUENCE SEQ_SITE
START WITH 1
INCREMENT BY 1
NOMAXVALUE;

ALTER TABLE HOUSING ADD (
  HOU_REASON_EXIT VARCHAR2(50 CHAR)
);
COMMENT ON COLUMN HOUSING.HOU_REASON_EXIT IS 'Motif de sortie, renseigné si date de sortie renseignée';

ALTER TABLE HOUSING ADD (
  HOU_GENERAL_COMMENT VARCHAR2(500 CHAR)
);
COMMENT ON COLUMN HOUSING.HOU_GENERAL_COMMENT IS 'Commentaire général sur le logement';

ALTER TABLE HOUSING ADD (
  HOU_LAST_DAAF_DATE DATE
);
COMMENT ON COLUMN HOUSING.HOU_LAST_DAAF_DATE IS 'Date de dernière maintenance DAAF';

ALTER TABLE HOUSING ADD (
  SIT_ID NUMBER(19,0)
);
COMMENT ON COLUMN HOUSING.SIT_ID IS 'Site en lien avec l''agence du logment';

ALTER TABLE TENANT ADD (
  TEN_PHONE VARCHAR2(20 CHAR)
);
COMMENT ON COLUMN TENANT.TEN_PHONE IS 'Numéro de téléphone de l''occupant';

ALTER TABLE TENANT ADD (
  TEN_MAIL_ADDRESS VARCHAR2(255 CHAR)
);
COMMENT ON COLUMN TENANT.TEN_MAIL_ADDRESS IS 'Adresse mail de l''occupant';

ALTER TABLE CONTRACT ADD (
  CON_INSURANCE_CERTIF_END_DATE DATE
);
COMMENT ON COLUMN CONTRACT.CON_INSURANCE_CERTIF_END_DATE IS 'Date limite de validité de l''attestation d''assurance';

-- la table CONTRACT n'est pas utilisée directement par hibernate, c'est la vue CONTRACT_DETAIL qui est utilisée
CREATE OR REPLACE FORCE VIEW CONTRACT_DETAIL (
  CON_ID,
  CON_REFERENCE,
  CON_SIGNATURE,
  CON_START_VALIDITY_DATE,
  CON_END_VALIDITY_DATE,
  CON_MARKET_RENT_PRICE,
  CON_RENT_PRICE_LIMIT,
  CON_GARAGE_RENT,
  CON_GARDEN_RENT,
  CON_EXTRA_RENT,
  CON_EXPECTED_CHARGE_COST,
  CON_ANNUAL_CLEARANCE_CHARGES,
  CON_GARBAGE_INVOICING,
  CON_WATER_INVOICING,
  CON_INSURANCE_REIMBURSEMENT,
  CON_HOUSING_TAX_REIMBURSEMENT,
  CON_GARBAGE_REIMBURSEMENT,
  CON_OTHER_INVOICING_LABEL,
  CON_OTHER_INVOICING_AMOUNT,
  CON_ADDED_WITHDRAWN_RENT,
  CON_LAST_WITHDRAWN_DATE,
  CON_TERMINATION_SAVINGS,
  CON_TERMINATION_SAVING_AMOUNT,
  CON_TERM_SAVINGS_PAYMENT,
  CON_TERM_SAVINGS_PAYMENT_DATE,
  CON_LAST_SAVING_DATE,
  CON_REAL_ESTATE_RENTAL_VALUE,
  CON_RETROACTIVITYS_MONTHS,
  HOU_ID,
  TEN_ID,
  RTP_ID,
  TER_ID,
  FIE_ID,
  CCE_ID,
  PME_ID,
  CON_NET_AGENT_RENT,
  CON_SHORTTERM_CONTRACT_DISCO,
  CON_LOP_RENT,
  CON_WITHDRAWN_RENT,
  CON_HOUSEHOLD_SIZE,
  CON_AGC_ID_FIX,
  CON_REVISED_SURF_AREA_FIX,
  CON_REVISED_SURF_AREA_RENT_FIX,
  CON_N_N_COEF_FIX,
  CON_LOP_RENT_FIX,
  CON_BENEFITS_FIX,
  CON_CLOSED,
  CON_INSURANCE_CERTIF_END_DATE,
  COD_REVISED_SURFACE_AREA,
  COD_REVISED_SURFACE_AREA_RENT,
  COD_N_N_COEF,
  COD_NET_AGENT_RENT,
  COD_SHORTTERM_CONTRACT_DISCO,
  COD_LOP_RENT,
  COD_WITHDRAWN_RENT,
  COD_ADDED_WITHDRAWN_RENT,
  COD_TERMINATION_SAVING_MONTH,
  COD_TERMINATION_SAVING_AMOUNT,
  COD_CALCULATED_BENEFITS)
AS
  SELECT
    C.CON_ID,
    C.CON_REFERENCE,
    C.CON_SIGNATURE,
    C.CON_START_VALIDITY_DATE,
    C.CON_END_VALIDITY_DATE,
    C.CON_MARKET_RENT_PRICE,
    C.CON_RENT_PRICE_LIMIT,
    C.CON_GARAGE_RENT,
    C.CON_GARDEN_RENT,
    C.CON_EXTRA_RENT,
    C.CON_EXPECTED_CHARGE_COST,
    C.CON_ANNUAL_CLEARANCE_CHARGES,
    CON_GARBAGE_INVOICING,
    CON_WATER_INVOICING,
    CON_INSURANCE_REIMBURSEMENT,
    CON_HOUSING_TAX_REIMBURSEMENT,
    CON_GARBAGE_REIMBURSEMENT,
    CON_OTHER_INVOICING_LABEL,
    CON_OTHER_INVOICING_AMOUNT,
    C.CON_ADDED_WITHDRAWN_RENT,
    C.CON_LAST_WITHDRAWN_DATE,
    C.CON_TERMINATION_SAVINGS,
    C.CON_TERMINATION_SAVING_AMOUNT,
    C.CON_TERM_SAVINGS_PAYMENT,
    C.CON_TERM_SAVINGS_PAYMENT_DATE,
    C.CON_LAST_SAVING_DATE,
    C.CON_REAL_ESTATE_RENTAL_VALUE,
    C.CON_RETROACTIVITYS_MONTHS,
    C.HOU_ID,
    C.TEN_ID,
    C.RTP_ID,
    C.TER_ID,
    C.FOA_ID,
    C.CCE_ID,
    C.PME_ID,
    C.CON_NET_AGENT_RENT,
    C.CON_SHORTTERM_CONTRACT_DISCO,
    C.CON_LOP_RENT,
    C.CON_WITHDRAWN_RENT,
    C.CON_HOUSEHOLD_SIZE,
    C.CON_AGC_ID_FIX,
    C.CON_REVISED_SURF_AREA_FIX,
    C.CON_REVISED_SURF_AREA_RENT_FIX,
    C.CON_N_N_COEF_FIX,
    C.CON_LOP_RENT_FIX,
    C.CON_BENEFITS_FIX,
    C.CON_CLOSED,
    C.CON_INSURANCE_CERTIF_END_DATE,
    H.HOU_REVISED_SURFACE_AREA                                                     AS COD_REVISED_SURFACE_AREA,
    VUE_LSC_CALC.LSC                                                               AS COD_REVISED_SURFACE_AREA_RENT,
    VUE_NN_COEF_CALC.NNCOEF                                                        AS COD_N_N_COEF,
    VUE_LNA_CALC.LNA                                                               AS COD_NET_AGENT_RENT,
    VUE_SHRTTRM_CNTRCT_DSC_CALC.STCD                                               AS COD_SHORTTERM_CONTRACT_DISCO,
    VUE_LOP_RENT_CALC.LOP_RENT                                                     AS COD_LOP_RENT,
    VUE_WITHDRAWN_RENT_CALC.WITHDRAWN_RENT                                         AS COD_WITHDRAWN_RENT,
    c.con_added_withdrawn_rent + VUE_WITHDRAWN_RENT_CALC.WITHDRAWN_RENT            AS COD_ADDED_WITHDRAWN_RENT,
    VUE_TERM_SAVING_MONTH_CALC.TERM_SAVING_MONTH                                   AS COD_TERMINATION_SAVING_MONTH,
    c.con_termination_saving_amount + VUE_TERM_SAVING_MONTH_CALC.TERM_SAVING_MONTH AS COD_TERMINATION_SAVING_AMOUNT,
    GET_CALCULATED_BENEFIT(t.ten_actual_salary, h.hou_room_count)                  AS COD_CALCULATED_BENEFITS
  FROM CONTRACT C
    JOIN HOUSING H
      ON C.HOU_ID = H.HOU_ID
    JOIN TENANT T
      ON C.TEN_ID = T.TEN_ID
    JOIN VUE_LSC_CALC
      ON C.CON_ID = VUE_LSC_CALC.CON_ID
    JOIN VUE_NN_COEF_CALC
      ON C.CON_ID = VUE_NN_COEF_CALC.CON_ID
    JOIN VUE_SHRTTRM_CNTRCT_DSC_CALC
      ON C.CON_ID = VUE_SHRTTRM_CNTRCT_DSC_CALC.CON_ID
    JOIN VUE_LOP_RENT_CALC
      ON C.CON_ID = VUE_LOP_RENT_CALC.CON_ID
    JOIN VUE_LNA_CALC
      ON C.CON_ID = VUE_LNA_CALC.CON_ID
    JOIN VUE_WITHDRAWN_RENT_CALC
      ON C.CON_ID = VUE_WITHDRAWN_RENT_CALC.CON_ID
    JOIN VUE_TERM_SAVING_MONTH_CALC
      ON C.CON_ID = VUE_TERM_SAVING_MONTH_CALC.CON_ID;
COMMIT;
