Alter Table Housing add (
HOU_FUTUR_OF_HOUSING VARCHAR2(50 CHAR),
HOU_DATE_FUT_OF_HOUSING VARCHAR2(4 CHAR),
HOU_PRICE NUMBER(8,0),
HOU_DATE_LAST_VISIT DATE,
HOU_SANITATION_STANDARDS VARCHAR2(50 CHAR),
HOU_FACADE VARCHAR2(50 CHAR),
HOU_COVER VARCHAR2(50 CHAR),
HOU_INSULATION VARCHAR2(50 CHAR),
HOU_WALLS VARCHAR2(50 CHAR),
HOU_JOINERY_FRAME VARCHAR2(50 CHAR),
HOU_INTERIOR_FINISHES VARCHAR2(50 CHAR),
HOU_VMC VARCHAR2(50 CHAR),
HOU_SANITARY_PLUMBING VARCHAR2(50 CHAR),
HOU_ENERGY_LABEL VARCHAR2(50 CHAR),
HOU_EMISSION_GES NUMBER(10,0),
HOU_DATE_PROGRAMMED_SALE VARCHAR2(4 CHAR),
HOU_DATE_PROGRAMMED_DEMOLITION VARCHAR2(4 CHAR),
HOU_COST_DEMOLITION NUMBER(8,0),
HOU_RENOVATION_DATE VARCHAR2(4 CHAR),
HOU_COST_RENOVATION NUMBER(8,0)
);

UPDATE FWK_PARAMETER
SET PRM_VALUE='02.05.00'
WHERE PRM_ID=3041;

commit;
exit;
