-- La table HISTORY_TENANT contenait des données corrompues en prod, donc inutilisable.
-- Pour corriger cela, on renomme la table HISTORY_TENANT afin de la recréer en suivant.
-- Les contraintes doivent être détruites puis recréer afin de rester cohérentes (le renommage d'une table renomme aussi les contraintes)
ALTER TABLE HISTORY_TENANT RENAME TO HISTORY_TENANT_OLD;
CREATE TABLE HISTORY_TENANT AS SELECT * FROM HISTORY_TENANT_OLD;
ALTER TABLE history_contract DROP CONSTRAINT "FK_HCO_2_HTE";
ALTER TABLE HISTORY_TENANT_OLD DROP CONSTRAINT "PK_HISTORY_TENANT";
ALTER TABLE HISTORY_TENANT_OLD DROP CONSTRAINT UK_TEN_MONTH_YEAR;
ALTER TABLE HISTORY_TENANT_OLD DROP CONSTRAINT FK_HTE_2_TEN;
ALTER TABLE HISTORY_TENANT ADD CONSTRAINT "PK_HISTORY_TENANT" PRIMARY KEY ("HTE_ID") USING INDEX TABLESPACE "TBS_ABITA_IDX";
ALTER TABLE HISTORY_TENANT ADD CONSTRAINT "UK_TEN_MONTH_YEAR" UNIQUE ("TEN_ID", "HTE_MONTH", "HTE_YEAR") USING INDEX TABLESPACE "TBS_ABITA_DAT";
ALTER TABLE HISTORY_TENANT ADD CONSTRAINT "FK_HTE_2_TEN" FOREIGN KEY ("TEN_ID") REFERENCES "ABITA"."TENANT" ("TEN_ID");
ALTER TABLE history_contract ADD CONSTRAINT "FK_HCO_2_HTE" FOREIGN KEY ("HTE_ID") REFERENCES "ABITA"."HISTORY_TENANT" ("HTE_ID");
ALTER INDEX PK_HISTORY_TENANT REBUILD;
ALTER INDEX UK_TEN_MONTH_YEAR REBUILD;
DROP TABLE HISTORY_TENANT_OLD;
