-- FWK_PARAMETER (Paramètre)
UPDATE FWK_PARAMETER SET PRM_VALUE = 'ABITA' WHERE PRM_NAME='siteName';
UPDATE FWK_PARAMETER SET PRM_VALUE = 'Administration des Baux Immobiliers des Tiers et des occupAnts' WHERE PRM_NAME='siteSubName';
UPDATE FWK_PARAMETER SET PRM_VALUE = '01.00.00' WHERE PRM_NAME='siteVersion';
UPDATE FWK_PARAMETER SET PRM_VALUE = 'sans groupe' WHERE PRM_NAME='defaultUserGroup';

INSERT INTO FWK_PARAMETER
VALUES (3300, 1, 'pathArchivesFolder', 'Path Archives Folder', 'Path to the Archives folder', '/applis/abita/archives/', '/applis/abita/archives/', 1001, 8, 1, 1, 'STRING');


-- FIELD_OF_ACTIVITY (Domaine d'activité)
INSERT INTO FIELD_OF_ACTIVITY
VALUES (SEQ_FIELD_OF_ACTIVITY.nextval, 'R0ME');


-- BENEFITS_LEVEL (Barème des avantages en nature)
INSERT INTO BENEFITS_LEVEL 
VALUES (SEQ_BENEFITS_LEVEL.nextval, 0, 66.70, 35.60);

INSERT INTO BENEFITS_LEVEL 
VALUES (SEQ_BENEFITS_LEVEL.nextval, 1564.50, 77.90, 50.00);

INSERT INTO BENEFITS_LEVEL 
VALUES (SEQ_BENEFITS_LEVEL.nextval, 1877.40, 88.90, 66.70);

INSERT INTO BENEFITS_LEVEL 
VALUES (SEQ_BENEFITS_LEVEL.nextval, 2190.30, 99.90, 83.30);

INSERT INTO BENEFITS_LEVEL 
VALUES (SEQ_BENEFITS_LEVEL.nextval, 2816.10, 122.30, 105.50);

INSERT INTO BENEFITS_LEVEL 
VALUES (SEQ_BENEFITS_LEVEL.nextval, 3441.90, 144.40, 127.70);

INSERT INTO BENEFITS_LEVEL 
VALUES (SEQ_BENEFITS_LEVEL.nextval, 4067.70, 166.60, 155.40);

INSERT INTO BENEFITS_LEVEL 
VALUES (SEQ_BENEFITS_LEVEL.nextval, 4693.50, 188.90, 177.80);


-- HOUSING_NATURE (Nature)
INSERT INTO HOUSING_NATURE
VALUES (SEQ_HOUSING_NATURE.nextval, 'Maison');

INSERT INTO HOUSING_NATURE
VALUES (SEQ_HOUSING_NATURE.nextval, 'Bâtiment');

INSERT INTO HOUSING_NATURE
VALUES (SEQ_HOUSING_NATURE.nextval, 'Appartement');

INSERT INTO HOUSING_NATURE
VALUES (SEQ_HOUSING_NATURE.nextval, 'Célibatorium');

INSERT INTO HOUSING_NATURE
VALUES (SEQ_HOUSING_NATURE.nextval, 'Garage');

INSERT INTO HOUSING_NATURE
VALUES (SEQ_HOUSING_NATURE.nextval, 'Autre');


-- ROOM_CATEGORY (Catégorie du local)
INSERT INTO ROOM_CATEGORY
VALUES (SEQ_ROOM_CATEGORY.nextval, 'I et Exceptionnel');

INSERT INTO ROOM_CATEGORY
VALUES (SEQ_ROOM_CATEGORY.nextval, '(I + II A) / 2');

INSERT INTO ROOM_CATEGORY
VALUES (SEQ_ROOM_CATEGORY.nextval, 'II A');

INSERT INTO ROOM_CATEGORY
VALUES (SEQ_ROOM_CATEGORY.nextval, '(II A + II B) / 2');

INSERT INTO ROOM_CATEGORY
VALUES (SEQ_ROOM_CATEGORY.nextval, 'II B');

INSERT INTO ROOM_CATEGORY
VALUES (SEQ_ROOM_CATEGORY.nextval, '(II B + II C) / 2');

INSERT INTO ROOM_CATEGORY
VALUES (SEQ_ROOM_CATEGORY.nextval, 'II C');

INSERT INTO ROOM_CATEGORY
VALUES (SEQ_ROOM_CATEGORY.nextval, '(II C + III A) / 2');

INSERT INTO ROOM_CATEGORY
VALUES (SEQ_ROOM_CATEGORY.nextval, 'III A');

INSERT INTO ROOM_CATEGORY
VALUES (SEQ_ROOM_CATEGORY.nextval, '(III A + III B) / 2');

INSERT INTO ROOM_CATEGORY
VALUES (SEQ_ROOM_CATEGORY.nextval, 'III B');


-- THIRD_PARTY_TERMINATION (Motif de résiliation)
INSERT INTO THIRD_PARTY_TERMINATION
VALUES (SEQ_THIRD_PARTY_TERMINATION.nextval, 'Résiliation du propriétaire');

INSERT INTO THIRD_PARTY_TERMINATION
VALUES (SEQ_THIRD_PARTY_TERMINATION.nextval, 'Résiliation RTE');


-- PAYMENT_CYCLE (Périodicité du paiment)
INSERT INTO PAYMENT_CYCLE
VALUES (SEQ_PAYMENT_CYCLE.nextval, 'Mensuel');

INSERT INTO PAYMENT_CYCLE
VALUES (SEQ_PAYMENT_CYCLE.nextval, 'Trimestriel');

INSERT INTO PAYMENT_CYCLE
VALUES (SEQ_PAYMENT_CYCLE.nextval, 'Annuel');


-- TYPE_TENANT (Type d'occupant)
INSERT INTO TYPE_TENANT
VALUES (SEQ_TYPE_TENANT.nextval, 'Salarié');

INSERT INTO TYPE_TENANT
VALUES (SEQ_TYPE_TENANT.nextval, 'Non salarié');

INSERT INTO TYPE_TENANT
VALUES (SEQ_TYPE_TENANT.nextval, 'Retraité');
