DROP TABLE ADJUSTMENT_RATE;

DROP SEQUENCE SEQ_ADJUSTMENT_RATE;

DROP TABLE CHARGE_TAX;

DROP SEQUENCE SEQ_CHARGE_TAX;

DROP TABLE FIELD;

DROP SEQUENCE SEQ_FIELD;

DROP TABLE RENT_TAX;

DROP SEQUENCE SEQ_RENT_TAX;

DROP TABLE RDD_ABITA;

DROP TABLE RDD_HOUSING;

DROP TABLE RDD_TENANT;

DROP TABLE RDD_THIRD_PARTY;

DROP TABLE RDD_THIRD_PARTY_CONTRACT;

DROP TABLE RDD_CONTRACT;