ALTER TABLE CONTRACT ADD (
	CON_LOP_RENT NUMBER(10,2)
	, CON_SHORTTERM_CONTRACT_DISCO NUMBER(10,2)
	, CON_N_N_COEF NUMBER(16,8)
	, CON_NET_AGENT_RENT NUMBER(10,2)
	, CON_WITHDRAWN_RENT NUMBER(10,2)
	);

-- Vue CONTRACT_DETAIL
CREATE OR REPLACE VIEW CONTRACT_DETAIL
	(CON_ID, CON_REFERENCE, CON_SIGNATURE, CON_START_VALIDITY_DATE, CON_END_VALIDITY_DATE, 
	 CON_MARKET_RENT_PRICE, CON_RENT_PRICE_LIMIT, CON_GARAGE_RENT, CON_GARDEN_RENT, CON_EXTRA_RENT, 
	 CON_EXPECTED_CHARGE_COST, CON_SPORADICALLY_INVOICING, 
	 CON_ADDED_WITHDRAWN_RENT, CON_LAST_WITHDRAWN_DATE, CON_TERMINATION_SAVINGS, 
	 CON_TERMINATION_SAVING_AMOUNT, CON_LAST_SAVING_DATE, CON_REAL_ESTATE_RENTAL_VALUE, HOU_ID, TEN_ID, 
	 RTP_ID, TER_ID, FIE_ID, CCE_ID, PME_ID, 
     CON_N_N_COEF, CON_NET_AGENT_RENT, CON_SHORTTERM_CONTRACT_DISCO, CON_LOP_RENT, CON_WITHDRAWN_RENT, 
	 COD_REVISED_SURFACE_AREA, COD_REVISED_SURFACE_AREA_RENT, COD_N_N_COEF, COD_NET_AGENT_RENT, COD_SHORTTERM_CONTRACT_DISCO, 
	 COD_LOP_RENT, COD_WITHDRAWN_RENT, COD_ADDED_WITHDRAWN_RENT, COD_TERMINATION_SAVING_MONTH, COD_TERMINATION_SAVING_AMOUNT,
	 COD_CALCULATED_BENEFITS )
	AS    
  SELECT 
    C.CON_ID, C.CON_REFERENCE, C.CON_SIGNATURE, C.CON_START_VALIDITY_DATE, C.CON_END_VALIDITY_DATE, 
    C.CON_MARKET_RENT_PRICE, C.CON_RENT_PRICE_LIMIT, C.CON_GARAGE_RENT, C.CON_GARDEN_RENT, C.CON_EXTRA_RENT, 
    C.CON_EXPECTED_CHARGE_COST, C.CON_SPORADICALLY_INVOICING, 
    C.CON_ADDED_WITHDRAWN_RENT, C.CON_LAST_WITHDRAWN_DATE, C.CON_TERMINATION_SAVINGS, 
    C.CON_TERMINATION_SAVING_AMOUNT, C.CON_LAST_SAVING_DATE, C.CON_REAL_ESTATE_RENTAL_VALUE, C.HOU_ID, C.TEN_ID, 
    C.RTP_ID, C.TER_ID, C.FOA_ID, C.CCE_ID, C.PME_ID ,
	C.CON_N_N_COEF, C.CON_NET_AGENT_RENT, C.CON_SHORTTERM_CONTRACT_DISCO, C.CON_LOP_RENT, C.CON_WITHDRAWN_RENT,    
    H.HOU_REVISED_SURFACE_AREA AS COD_REVISED_SURFACE_AREA,
    VUE_LSC_CALC.LSC AS COD_REVISED_SURFACE_AREA_RENT,
    VUE_NN_COEF_CALC.NNCOEF AS COD_N_N_COEF,
    VUE_LNA_CALC.LNA AS COD_NET_AGENT_RENT,
    VUE_SHRTTRM_CNTRCT_DSC_CALC.STCD AS COD_SHORTTERM_CONTRACT_DISCO,
    VUE_LOP_RENT_CALC.LOP_RENT AS COD_LOP_RENT,
    VUE_WITHDRAWN_RENT_CALC.WITHDRAWN_RENT AS COD_WITHDRAWN_RENT,
    c.con_added_withdrawn_rent + VUE_WITHDRAWN_RENT_CALC.WITHDRAWN_RENT AS COD_ADDED_WITHDRAWN_RENT,
    VUE_TERM_SAVING_MONTH_CALC.TERM_SAVING_MONTH AS COD_TERMINATION_SAVING_MONTH,
    c.con_termination_saving_amount + VUE_TERM_SAVING_MONTH_CALC.TERM_SAVING_MONTH AS COD_TERMINATION_SAVING_AMOUNT,
    GET_CALCULATED_BENEFIT(t.ten_actual_salary, h.hou_room_count) AS COD_CALCULATED_BENEFITS
  FROM CONTRACT C
  JOIN HOUSING H on C.HOU_ID = H.HOU_ID
  JOIN TENANT T on C.TEN_ID = T.TEN_ID
  JOIN VUE_LSC_CALC on C.CON_ID = VUE_LSC_CALC.CON_ID
  JOIN VUE_NN_COEF_CALC on C.CON_ID = VUE_NN_COEF_CALC.CON_ID
  JOIN VUE_SHRTTRM_CNTRCT_DSC_CALC on C.CON_ID = VUE_SHRTTRM_CNTRCT_DSC_CALC.CON_ID
  JOIN VUE_LOP_RENT_CALC on C.CON_ID = VUE_LOP_RENT_CALC.CON_ID
  JOIN VUE_LNA_CALC on C.CON_ID = VUE_LNA_CALC.CON_ID
  JOIN VUE_WITHDRAWN_RENT_CALC on C.CON_ID = VUE_WITHDRAWN_RENT_CALC.CON_ID
  JOIN VUE_TERM_SAVING_MONTH_CALC on C.CON_ID = VUE_TERM_SAVING_MONTH_CALC.CON_ID;
/
  

CREATE OR REPLACE VIEW VUE_LOP_RENT_CALC (CON_ID, LOP_RENT)
AS
  SELECT C.CON_ID,
    ROUND(NVL(T.ten_reference_gross_salary,0) * 0.15,3) AS LOP_RENT
  FROM CONTRACT C
  JOIN TENANT T
  ON C.TEN_ID = T.TEN_ID;
  
CREATE OR REPLACE VIEW VUE_LNA_CALC (CON_ID, LNA)
AS
  SELECT C.CON_ID,
    ROUND(DECODE(RT.rtp_technical_code, 'LAS', LEAST(C.CON_N_N_COEF * (VUE_LSC_CALC.LSC - VUE_SHRTTRM_CNTRCT_DSC_CALC.STCD), C.CON_LOP_RENT), 'LMA', NVL(C.CON_MARKET_RENT_PRICE,0), 'LBA', LEAST(VUE_LSC_CALC.LSC - NVL(VUE_SHRTTRM_CNTRCT_DSC_CALC.STCD,0), C.CON_LOP_RENT), NVL(C.CON_RENT_PRICE_LIMIT,0)),2) AS LNA
  FROM CONTRACT C
  JOIN RENT_TYPOLOGY RT
  ON C.RTP_ID = RT.RTP_ID
  JOIN VUE_LSC_CALC
  ON C.CON_ID = VUE_LSC_CALC.CON_ID
  JOIN VUE_SHRTTRM_CNTRCT_DSC_CALC
  ON C.CON_ID = VUE_SHRTTRM_CNTRCT_DSC_CALC.CON_ID;
/

CREATE OR REPLACE VIEW VUE_LOP_RENT_CALC (CON_ID, LOP_RENT)
AS
  SELECT C.CON_ID,
    ROUND(NVL(T.ten_reference_gross_salary,0) * 0.15,2) AS LOP_RENT
  FROM CONTRACT C
  JOIN TENANT T
  ON C.TEN_ID = T.TEN_ID;
/
  
CREATE OR REPLACE VIEW VUE_LSC_CALC (CON_ID, LSC)
AS
  SELECT C.CON_ID,
    ROUND((LEAST(h.hou_revised_surface_area, 10) * rc.rca_first_10_sqr_meter_price) + (GREATEST(h.hou_revised_surface_area - 10, 0) * rc.rca_next_sqr_meter_price),2) AS LSC
  FROM CONTRACT C
  JOIN HOUSING H
  ON C.HOU_ID = H.HOU_ID
  JOIN ROOM_CATEGORY RC
  ON H.RCA_ID = RC.RCA_ID;
/
  
CREATE OR REPLACE VIEW VUE_NN_COEF_CALC (CON_ID, NNCOEF)
AS
  SELECT C.CON_ID,
    ROUND((t.TEN_HOUSEHOLD_SIZE_LAST_YEAR + DECODE(T.TEN_MANAGERIAL_EMP_LAST_YEAR, '1', 1, 0)) / NULLIF(h.hou_room_count + DECODE(rt.rtp_technical_code, 'LAS', 1, 0),0),8) AS NNCOEF
  FROM CONTRACT C
  JOIN RENT_TYPOLOGY RT
  ON C.RTP_ID = RT.RTP_ID
  JOIN HOUSING H
  ON C.HOU_ID = H.HOU_ID
  JOIN TENANT T
  ON C.TEN_ID = T.TEN_ID;
/
  
CREATE OR REPLACE VIEW VUE_SHRTTRM_CNTRCT_DSC_CALC (CON_ID, STCD)
AS
  SELECT LSC_C.CON_ID,
    ROUND(LSC_C.LSC * 0.075,2) AS STCD
  FROM VUE_LSC_CALC LSC_C;
/
  
CREATE OR REPLACE VIEW VUE_TERM_SAVING_MONTH_CALC (CON_ID, TERM_SAVING_MONTH)
AS
  SELECT C.CON_ID,
    ROUND((VUE_LNA_CALC.LNA + NVL(C.con_garden_rent,0)) * 0.075,2) AS TERM_SAVING_MONTH
  FROM CONTRACT C
  JOIN VUE_LNA_CALC
  ON C.CON_ID = VUE_LNA_CALC.CON_ID;
/
  
CREATE OR REPLACE VIEW VUE_WITHDRAWN_RENT_CALC (CON_ID, WITHDRAWN_RENT)
AS
  SELECT C.CON_ID,
    ROUND(VUE_LNA_CALC.LNA + NVL(C.con_garage_rent,0) + (NVL(C.con_garden_rent,0) - 0.075 * NVL(C.con_garden_rent,0)) + NVL(C.con_extra_rent,0) + NVL(C.con_expected_charge_cost,0) + NVL(C.con_sporadically_invoicing,0),2) AS WITHDRAWN_RENT
  FROM CONTRACT C
  JOIN VUE_LNA_CALC
  ON C.CON_ID = VUE_LNA_CALC.CON_ID;
/


UPDATE FWK_PARAMETER SET PRM_VALUE = '/applis/abita/temp/Artesis/{0}' WHERE PRM_NAME = 'artesisNniTempFileName';
UPDATE FWK_PARAMETER SET PRM_VALUE = '/applis/abita/temp/Artesis/{0}.txt' WHERE PRM_NAME = 'artesisTempFileName';

