UPDATE FWK_PARAMETER SET PRM_VALUE = '02.04.00' WHERE PRM_ID = '3041';


ALTER TABLE HOUSING ADD (
  HOU_SANITATION NUMBER(19,0),
  HOU_HEATING_TYPE NUMBER(19,0),
  HOU_AIRCONDITIONER NUMBER(19,0),
  HOU_OI_HOUSING VARCHAR2(10 CHAR),
  HOU_EOTP VARCHAR2(20 CHAR),
  HOU_EQUIPPED_KITCHEN VARCHAR2(1 CHAR),
  HOU_KITCHEN_DATE DATE,
  HOU_BATHROOM VARCHAR2(1 CHAR),
  HOU_BATHROOM_DATE DATE,
  HOU_DPE VARCHAR2(1 CHAR),
  HOU_DPE_DATE DATE,
  HOU_GAS VARCHAR2(1 CHAR),
  HOU_GAS_DATE DATE,
  HOU_GAS_ANO VARCHAR2(1 CHAR),
  HOU_ELECT VARCHAR2(1 CHAR),
  HOU_ELECT_DATE DATE,
  HOU_ELECT_ANO VARCHAR2(1 CHAR),
  HOU_ASBESTOS VARCHAR2(1 CHAR),
  HOU_ASBESTOS_DATE DATE,
  HOU_ASBESTOS_ANO VARCHAR2(1 CHAR),
  HOU_LEAD VARCHAR2(1 CHAR),
  HOU_LEAD_DATE DATE,
  HOU_LEAD_ANO VARCHAR2(1 CHAR),
  HOU_TERMITE VARCHAR2(1 CHAR),
  HOU_TERMITE_DATE DATE,
  HOU_TERMITE_ANO VARCHAR2(1 CHAR),
  HOU_ERNMT VARCHAR2(1 CHAR),
  HOU_ERNMT_DATE DATE,
  HOU_CARREZ VARCHAR2(1 CHAR),
  HOU_CARREZ_DATE DATE,
  HOU_SQUARE_METER NUMBER(10,3)
);

-- SANITATION
CREATE TABLE SANITATION (	san_id NUMBER(19,0) not null, san_label VARCHAR2(50 CHAR) not null,
  CONSTRAINT pk_sanitation PRIMARY KEY (san_id) USING INDEX TABLESPACE TBS_ABITA_IDX);

-- SEQUENCE SANITATION
CREATE SEQUENCE SEQ_SANITATION
START WITH 1
INCREMENT BY 1
NOMAXVALUE;

-- COMMENT SANITATION
COMMENT ON TABLE SANITATION IS 'Assainissement';

INSERT INTO SANITATION (SAN_ID, SAN_LABEL) VALUES (SEQ_SANITATION.nextval, 'Réseau séparé');
INSERT INTO SANITATION (SAN_ID, SAN_LABEL) VALUES (SEQ_SANITATION.nextval, 'Tout à l''égout');
INSERT INTO SANITATION (SAN_ID, SAN_LABEL) VALUES (SEQ_SANITATION.nextval, 'Fosse septique');
INSERT INTO SANITATION (SAN_ID, SAN_LABEL) VALUES (SEQ_SANITATION.nextval, 'Epandage');
INSERT INTO SANITATION (SAN_ID, SAN_LABEL) VALUES (SEQ_SANITATION.nextval, 'Inconnu');



-- HEATING_TYPE
CREATE TABLE HEATING_TYPE (	ht_id NUMBER(19,0) not null, ht_label VARCHAR2(50 CHAR) not null,
  CONSTRAINT pk_heating_type PRIMARY KEY (ht_id) USING INDEX TABLESPACE TBS_ABITA_IDX);

-- SEQUENCE HEATING_TYPE
CREATE SEQUENCE SEQ_HEATING_TYPE
START WITH 1
INCREMENT BY 1
NOMAXVALUE;

-- COMMENT HEATING_TYPE
COMMENT ON TABLE HEATING_TYPE IS 'Type de chauffage';

INSERT INTO HEATING_TYPE (HT_ID, HT_LABEL) VALUES (SEQ_HEATING_TYPE.nextval, 'Gaz');
INSERT INTO HEATING_TYPE (HT_ID, HT_LABEL) VALUES (SEQ_HEATING_TYPE.nextval, 'Electricité');
INSERT INTO HEATING_TYPE (HT_ID, HT_LABEL) VALUES (SEQ_HEATING_TYPE.nextval, 'Fuel');
INSERT INTO HEATING_TYPE (HT_ID, HT_LABEL) VALUES (SEQ_HEATING_TYPE.nextval, 'Autre');
INSERT INTO HEATING_TYPE (HT_ID, HT_LABEL) VALUES (SEQ_HEATING_TYPE.nextval, 'Inconnu');


-- AIRCONDITIONER
CREATE TABLE AIRCONDITIONER (	ac_id NUMBER(19,0) not null, ac_label VARCHAR2(50 CHAR) not null,
  CONSTRAINT pk_airconditioner PRIMARY KEY (ac_id) USING INDEX TABLESPACE TBS_ABITA_IDX);

-- SEQUENCE AIRCONDITIONER
CREATE SEQUENCE SEQ_AIRCONDITIONER
START WITH 1
INCREMENT BY 1
NOMAXVALUE;

-- COMMENT AIRCONDITIONER
COMMENT ON TABLE AIRCONDITIONER IS 'Climatiseur';

INSERT INTO AIRCONDITIONER (AC_ID, AC_LABEL) VALUES (SEQ_AIRCONDITIONER.nextval, 'Oui');
INSERT INTO AIRCONDITIONER (AC_ID, AC_LABEL) VALUES (SEQ_AIRCONDITIONER.nextval, 'Non');
INSERT INTO AIRCONDITIONER (AC_ID, AC_LABEL) VALUES (SEQ_AIRCONDITIONER.nextval, 'Inconnu');

COMMIT;
